export { clone } from './clone'
export { pull } from './pull'
export { push } from './push'
export { status } from './status'
export { commit } from './commit'
export { identity } from './identity'
export { exec } from './exec'
export { spawn } from './spawn'
